### ISSUE TITLE
Collaboration with colab?

### ISSUE THREAD

**Issue by montagne5641** [Kazuhito00/yolox-bytetrack-mcmot-sample#1]
i think it's a very interesting test, and  wonder if there's any way you could consider working with the colab environment? thank you.

**Comment by Kazuhito00** [comment]
Have you tried anything yourself?
It will work with Colab if you install the required packages.

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.
